version: '3'

services:
  php-symfo:
    container_name: php-symfo
    build:
      context: ./php-symfo
      dockerfile: Dockerfile
    ports:
      - "9000:8000"
    volumes:
      - .:/var/www/html

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/db_data:rw

volumes:
###> doctrine/doctrine-bundle ###
  db_data:
###< doctrine/doctrine-bundle ###
